### ISSUE TITLE
Possible memory leak issue

### ISSUE THREAD

**Issue by jcbmao** [bdzwillo/wrapfs_nfs#3]
Hello! I tested using wrapfs for a while and found that the kernel seen by free is not enough, but the memory occupied by the application program is not much. Is it possible that there is a memory leak in the wrapfs kernel module? 
The tested kernel version is 4.19.90.

**Comment by bdzwillo** [comment]
There is no memory leak I am aware of in the configurations where wrapfs runs with a redhat-7/8/9 kernel on top of nfs. On some busy servers the module runs for months without a noticeable increase in memory consumption.

Since 4.19.90 does not look like a redhat kernel, there might exists issues with the kernel API or the filesystem configuration in your setup.
- did you test if 'rmmod' works cleanly after unmount, and if the memory leak you see still persists?
- do you have any idea which kind of operation or syscall might cause the memory leak in your configuration?
